### ISSUE TITLE
This action sometimes suggests downgrades

### ISSUE THREAD

**Issue by starikcetin** [saadmk11/github-actions-version-updater#25] opened 2022-10-20 09:26 UTC
Sometimes actions backport some features to previous major versions, and this action is offering them in the PRs, essentially meaning it would downgrade the version if merged. 

As far as I understand this is due to not parsing the version and just looking at the latest release in terms of date. I recommend parsing the version and comparing them numerically to decide whether a version is newer or not.

**Comment by SebastianStehle** [comment] 2022-10-20 10:19
Have you seen this one: https://github.com/saadmk11/github-actions-version-updater/issues/20

**Comment by saadmk11** [comment] 2022-10-20 10:34
Hi @starikcetin, Thanks for creating the issue, The fix (https://github.com/saadmk11/github-actions-version-updater/pull/19) is already merged to the main branch. Please try it out using  `saadmk11/github-actions-version-updater@main` and let me know if it solves the issue you are facing. 

I am planning to do a release tomorrow or on this weekend :)

**Comment by saadmk11** [comment] 2022-10-22 14:37
Closing the issue as the changes has been released. https://github.com/saadmk11/github-actions-version-updater/releases/tag/v0.7.0

Feel free to Re-Open if the issue is not fixed. :)

**Closed by saadmk11** 2022-10-22 14:37 UTC
