### ISSUE TITLE
Do not update  "azure/login" to last version

### ISSUE THREAD

**Issue by hocinemala** [saadmk11/github-actions-version-updater#64] opened 2023-03-06 21:36 UTC
Hello,

I ran the composite action updater and I noticed the tool proposed to update the action "azure/login" to the version v1.4.6 although  the version was already the last v1.4.7
So It is proposing a downgrade because from v1.4.7 to v1.4.6

![image](https://user-images.githubusercontent.com/47140149/223236063-353cc5d0-ab1e-457a-8e2f-455f5fb602fe.png)

Regards
Hme

**Comment by saadmk11** [comment] 2023-03-12 14:05
This GH Action uses the GitHub's Releases API to find the latest release but it looks like release `v1.4.7` was removed for some reason. 

It is not visible in the marketplace page as well:

![Screenshot from 2023-03-12 20-04-43](https://user-images.githubusercontent.com/24854406/224549760-62876610-96c6-41ba-ac7a-79b068f94c65.png)


Ref: 
- https://api.github.com/repos/Azure/login/releases
- https://github.com/Azure/login/releases

**Comment by saadmk11** [comment] 2023-03-12 14:11
I am closing this for now as I think this is expected behavior. But please feel free to re-open it if this happens on other updates that has the version on their releases page.

**Closed by saadmk11** 2023-03-12 14:11 UTC
